# Generated by Django 4.2.1 on 2023-06-01 20:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qte_stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.categorie')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.size')),
                ('subcategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.subcategorie')),
            ],
        ),
    ]
