# Generated by Django 4.2.1 on 2023-06-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('Cin_Number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=355)),
                ('phone_Number', models.IntegerField()),
                ('email', models.CharField(max_length=355)),
            ],
        ),
    ]
